INSERT INTO employee(name,email,telephone) VALUES('Dwight D. Eisenhower','dEisenhower@ww2.com','787-852-412');
INSERT INTO employee(name,email,telephone) VALUES('Douglas MacArthur','dMacArthur@ww2.com','787-851-412');
INSERT INTO employee(name,email,telephone) VALUES('Mark W. Clark','mClark@ww2.com','787-852-412');
INSERT INTO employee(name,email,telephone) VALUES('George S. Patton, Jr.','gsPatton@ww2.com','787-852-412');
INSERT INTO employee(name,email,telephone) VALUES('Anne Frank','afrank@ww2.com','787-852-412');
INSERT INTO employee(name,email,telephone) VALUES('Oskar Schindler','oSchindler@ww2.com','787-852-123');
INSERT INTO employee(name,email,telephone) VALUES('Winston Churchill','wChurchill@ww2.com','787-852-413');
INSERT INTO employee(name,email,telephone) VALUES('Hirohito','Hirohito@ww2.com','187-852-412');
INSERT INTO employee(name,email,telephone) VALUES('Abraham, Erich','EAbraham.Germany@ww2.com','522-421-337');
INSERT INTO employee(name,email,telephone) VALUES('Abrams, Creighton','CAbrams.United States@ww2.com','55-476-245');
INSERT INTO employee(name,email,telephone) VALUES('Adachi, Hatazo','HAdachi.Japan@ww2.com','606-501-948');
INSERT INTO employee(name,email,telephone) VALUES('Adler, Julius','JAdler.United States@ww2.com','515-261-97');
INSERT INTO employee(name,email,telephone) VALUES('Aho, Martti','MAho.Finland@ww2.com','596-499-366');
INSERT INTO employee(name,email,telephone) VALUES('Airo, Aksel','AAiro.Finland@ww2.com','626-717-705');
INSERT INTO employee(name,email,telephone) VALUES('Alexander, Harold','HAlexander.United Kingdom@ww2.com','238-614-493');
INSERT INTO employee(name,email,telephone) VALUES('Allen, Arthur','AAllen.Australia@ww2.com','665-559-379');
INSERT INTO employee(name,email,telephone) VALUES('Allen, Terry','TAllen.United States@ww2.com','702-185-375');
INSERT INTO employee(name,email,telephone) VALUES('Anami, Korechika','KAnami.Japan@ww2.com','559-337-459');
INSERT INTO employee(name,email,telephone) VALUES('Anders, Waadysaaw','WAnders.Poland@ww2.com','702-11-770');
INSERT INTO employee(name,email,telephone) VALUES('Ando, Rikichi','RAndo.Japan@ww2.com','214-288-129');
INSERT INTO employee(name,email,telephone) VALUES('Arms, Thomas','TArms.United States@ww2.com','770-708-666');
INSERT INTO employee(name,email,telephone) VALUES('Auchinleck, Claude','CAuchinleck.United Kingdom@ww2.com','207-3-697');
INSERT INTO employee(name,email,telephone) VALUES('Avramescu, Gheorghe','GAvramescu.Romania@ww2.com','594-614-432');
INSERT INTO employee(name,email,telephone) VALUES('Babadzhanian, Hamazasp','HBabadzhanian.Armenia@ww2.com','428-565-684');
INSERT INTO employee(name,email,telephone) VALUES('Badoglio, Pietro','PBadoglio.Italy@ww2.com','551-326-349');
INSERT INTO employee(name,email,telephone) VALUES('Bagramyan, Ivan','IBagramyan.Armenia@ww2.com','821-799-664');
INSERT INTO employee(name,email,telephone) VALUES('Bai, Chongxi','CBai.China@ww2.com','467-138-195');
INSERT INTO employee(name,email,telephone) VALUES('Baker, Vernon','VBaker.United States@ww2.com','865-36-140');
INSERT INTO employee(name,email,telephone) VALUES('Basilone, John','JBasilone.United States@ww2.com','718-223-57');
INSERT INTO employee(name,email,telephone) VALUES('Bastin, Jules','JBastin.Belgium@ww2.com','898-879-185');
INSERT INTO employee(name,email,telephone) VALUES('Beck, Ludwig','LBeck.Germany@ww2.com','132-410-442');
INSERT INTO employee(name,email,telephone) VALUES('Bennett, Donald','DBennett.United States@ww2.com','536-817-535');
INSERT INTO employee(name,email,telephone) VALUES('Bennett, Gordon','GBennett.Australia@ww2.com','709-523-705');
INSERT INTO employee(name,email,telephone) VALUES('Bie, Tingfang','TBie.China@ww2.com','858-952-835');
INSERT INTO employee(name,email,telephone) VALUES('Bismarck, Georg','GBismarck.Germany@ww2.com','747-565-364');
INSERT INTO employee(name,email,telephone) VALUES('Blamey, Thomas','TBlamey.Australia@ww2.com','281-459-294');
INSERT INTO employee(name,email,telephone) VALUES('Blaskowitz, Johannes','JBlaskowitz.Germany@ww2.com','292-699-508');
INSERT INTO employee(name,email,telephone) VALUES('Blomberg, Werner','WBlomberg.Germany@ww2.com','635-169-610');
INSERT INTO employee(name,email,telephone) VALUES('Bock, Fedor','FBock.Germany@ww2.com','994-190-612');
INSERT INTO employee(name,email,telephone) VALUES('Bohusz-Szyszko, Zygmunt','ZBohusz-Szyszko.Poland@ww2.com','759-460-559');
INSERT INTO employee(name,email,telephone) VALUES('Bradley, Omar','OBradley.United States@ww2.com','411-801-307');
INSERT INTO employee(name,email,telephone) VALUES('Brandenberger, Erich','EBrandenberger.Germany@ww2.com','615-995-174');
INSERT INTO employee(name,email,telephone) VALUES('Brandt, Heinz','HBrandt.Germany@ww2.com','322-683-799');
INSERT INTO employee(name,email,telephone) VALUES('Brauchitsch, Walther','WBrauchitsch.Germany@ww2.com','125-282-785');
INSERT INTO employee(name,email,telephone) VALUES('Briesen, Kurt','KBriesen.Germany@ww2.com','571-848-488');
INSERT INTO employee(name,email,telephone) VALUES('Brooke, Alan','ABrooke.United Kingdom@ww2.com','648-276-150');
INSERT INTO employee(name,email,telephone) VALUES('Brooks, Edward','EBrooks.United States@ww2.com','889-372-73');
INSERT INTO employee(name,email,telephone) VALUES('Browning, Frederick','FBrowning.United Kingdom@ww2.com','115-320-777');
INSERT INTO employee(name,email,telephone) VALUES('Buckner, Simon','SBuckner.United States@ww2.com','277-120-567');
INSERT INTO employee(name,email,telephone) VALUES('Budyonny, Semyon','SBudyonny.Russia@ww2.com','616-965-820');
INSERT INTO employee(name,email,telephone) VALUES('Buhle, Walther','WBuhle.Germany@ww2.com','973-977-85');
INSERT INTO employee(name,email,telephone) VALUES('Burgdorf, Wilhelm ','WBurgdorf.Germany@ww2.com','344-611-311');
INSERT INTO employee(name,email,telephone) VALUES('Cai, Tingkai','TCai.China@ww2.com','102-828-683');
INSERT INTO employee(name,email,telephone) VALUES('Cates, Clifton','CCates.United States@ww2.com','476-313-781');
INSERT INTO employee(name,email,telephone) VALUES('Catlos, Ferdinand','FCatlos.Czechoslovakia@ww2.com','582-340-536');
INSERT INTO employee(name,email,telephone) VALUES('Cavallero, Ugo','UCavallero.Italy@ww2.com','362-768-766');
INSERT INTO employee(name,email,telephone) VALUES('Chen Changjie','CChe.China@ww2.com','25-235-39');
INSERT INTO employee(name,email,telephone) VALUES('Chen, Cheng','CChen.China@ww2.com','960-319-966');
INSERT INTO employee(name,email,telephone) VALUES('Chen, Daqing','DChen.China@ww2.com','415-441-916');
INSERT INTO employee(name,email,telephone) VALUES('Chen, Mingshu','MChen.China@ww2.com','759-55-69');
INSERT INTO employee(name,email,telephone) VALUES('Chen, Yi','YChen.China@ww2.com','741-444-223');
INSERT INTO employee(name,email,telephone) VALUES('Chuikov, Vasily','VChuikov.Russia@ww2.com','225-245-686');
INSERT INTO employee(name,email,telephone) VALUES('Chung, Il-kwon','IChung.Korea@ww2.com','72-204-381');
INSERT INTO employee(name,email,telephone) VALUES('Clark, Mark','MClark.United States@ww2.com','767-812-629');
INSERT INTO employee(name,email,telephone) VALUES('Cochrane, Archibald','ACochrane.United Kingdom@ww2.com','82-206-461');
INSERT INTO employee(name,email,telephone) VALUES('Crerar, Henry','HCrerar.Canada@ww2.com','792-367-718');
INSERT INTO employee(name,email,telephone) VALUES('Davis, Benjamin','BDavis.United States@ww2.com','294-606-135');
INSERT INTO employee(name,email,telephone) VALUES('de Lattre de Tassigny, Jean','Ld.France@ww2.com','363-534-369');
INSERT INTO employee(name,email,telephone) VALUES('del Valle, Pedro','Vde.Puerto Rico@ww2.com','333-544-839');
INSERT INTO employee(name,email,telephone) VALUES('Dempsey, Miles','MDempsey.United Kingdom@ww2.com','4-479-566');
INSERT INTO employee(name,email,telephone) VALUES('Deng, Xihou','XDeng.China@ww2.com','102-369-217');
INSERT INTO employee(name,email,telephone) VALUES('Dentz, Henri','HDentz.France@ww2.com','6-25-486');
INSERT INTO employee(name,email,telephone) VALUES('Derevyanko, Kuzma','KDerevyanko.Ukraine@ww2.com','333-964-120');
INSERT INTO employee(name,email,telephone) VALUES('Devers, Jacob','JDevers.United States@ww2.com','507-308-833');
INSERT INTO employee(name,email,telephone) VALUES('Dietl, Eduard','EDietl.Germany@ww2.com','841-593-785');
INSERT INTO employee(name,email,telephone) VALUES('Dietrich, Josef','JDietrich.Germany@ww2.com','16-15-285');
INSERT INTO employee(name,email,telephone) VALUES('Dimoline, Harry','HDimoline.United Kingdom@ww2.com','504-962-104');
INSERT INTO employee(name,email,telephone) VALUES('Dimoline, William','WDimoline.United Kingdom@ww2.com','433-268-546');
INSERT INTO employee(name,email,telephone) VALUES('Ding, Delong','DDing.China@ww2.com','56-664-999');
INSERT INTO employee(name,email,telephone) VALUES('Doihara, Kenji','KDoihara.Japan@ww2.com','424-642-684');
INSERT INTO employee(name,email,telephone) VALUES('Dong, Zhao','ZDong.China@ww2.com','772-817-7');
INSERT INTO employee(name,email,telephone) VALUES('Doss, Desmond','DDoss.United States@ww2.com','384-571-537');
INSERT INTO employee(name,email,telephone) VALUES('Dostler, Anton','ADostler.Germany@ww2.com','274-851-273');
INSERT INTO employee(name,email,telephone) VALUES('Du, Yuming','YDu.China@ww2.com','563-642-874');
INSERT INTO employee(name,email,telephone) VALUES('Dumitrescu, Petre','PDumitrescu.Romania@ww2.com','285-857-860');
INSERT INTO employee(name,email,telephone) VALUES('Eddy, Manton','MEddy.United States@ww2.com','255-979-300');
INSERT INTO employee(name,email,telephone) VALUES('Eichelberger, Robert','REichelberger.United States@ww2.com','937-864-924');
INSERT INTO employee(name,email,telephone) VALUES('Eisenhower, Dwight','DEisenhower.United States@ww2.com','68-185-303');
INSERT INTO employee(name,email,telephone) VALUES('Emmons, Delos','DEmmons.United States@ww2.com','974-159-304');
INSERT INTO employee(name,email,telephone) VALUES('Erskine, Graves','GErskine.United States@ww2.com','613-687-322');
INSERT INTO employee(name,email,telephone) VALUES('Esteban Infantes, Emilio','IEsteba.Spain@ww2.com','410-422-567');
INSERT INTO employee(name,email,telephone) VALUES('Falkenhausen, Alexander','AFalkenhausen.Germany@ww2.com','870-65-968');
INSERT INTO employee(name,email,telephone) VALUES('Falkenhorst, Nikolaus','NFalkenhorst.Germany@ww2.com','605-342-493');
INSERT INTO employee(name,email,telephone) VALUES('Felmy, Hellmuth','HFelmy.Germany@ww2.com','480-189-339');
INSERT INTO employee(name,email,telephone) VALUES('Fretter-Pico, Maximilian','MFretter-Pico.Germany@ww2.com','74-623-208');
INSERT INTO employee(name,email,telephone) VALUES('Freyberg, Bernard','BFreyberg.New Zealand@ww2.com','1-72-929');
INSERT INTO employee(name,email,telephone) VALUES('Fritsch, Werner','WFritsch.Germany@ww2.com','766-703-932');
INSERT INTO employee(name,email,telephone) VALUES('Fu, Zuoyi','ZFu.China@ww2.com','24-779-411');
INSERT INTO employee(name,email,telephone) VALUES('Furman, Robert','RFurman.United States@ww2.com','280-273-656');
INSERT INTO employee(name,email,telephone) VALUES('Furusho, Mikio','MFurusho.Japan@ww2.com','793-25-288');
INSERT INTO employee(name,email,telephone) VALUES('Gabaldon, Guy','GGabaldon.United States@ww2.com','256-478-160');
INSERT INTO employee(name,email,telephone) VALUES('Gamelin, Maurice','MGamelin.France@ww2.com','55-16-889');
INSERT INTO employee(name,email,telephone) VALUES('Gavin, James','JGavin.United States@ww2.com','332-410-913');
INSERT INTO employee(name,email,telephone) VALUES('Gehlen, Reinhard','RGehlen.Germany@ww2.com','483-480-201');
INSERT INTO employee(name,email,telephone) VALUES('Geiger, Roy','RGeiger.United States@ww2.com','67-948-33');
INSERT INTO employee(name,email,telephone) VALUES('Geloso, Carlo','CGeloso.Italy@ww2.com','461-146-744');
INSERT INTO employee(name,email,telephone) VALUES('Gerow, Leonard','LGerow.United States@ww2.com','487-219-463');
INSERT INTO employee(name,email,telephone) VALUES('Giffard, George','GGiffard.United Kingdom@ww2.com','91-111-315');
INSERT INTO employee(name,email,telephone) VALUES('Giraud, Henri','HGiraud.France@ww2.com','525-645-400');
INSERT INTO employee(name,email,telephone) VALUES('Golikov, Filipp','FGolikov.Russia@ww2.com','154-210-9');
INSERT INTO employee(name,email,telephone) VALUES('Graziani, Rodolfo','RGraziani.Italy@ww2.com','170-125-920');
INSERT INTO employee(name,email,telephone) VALUES('Greyeyes, Mary','MGreyeyes.Canada@ww2.com','117-942-2');
INSERT INTO employee(name,email,telephone) VALUES('Groves, Leslie','LGroves.United States@ww2.com','918-128-584');
INSERT INTO employee(name,email,telephone) VALUES('Gu, Zhutong','ZGu.China@ww2.com','451-903-267');
INSERT INTO employee(name,email,telephone) VALUES('Guderian, Heinz','HGuderian.Germany@ww2.com','157-99-493');
INSERT INTO employee(name,email,telephone) VALUES('Halder, Franz','FHalder.Germany@ww2.com','228-602-850');
INSERT INTO employee(name,email,telephone) VALUES('Han, Deqin','DHan.China@ww2.com','472-533-882');
INSERT INTO employee(name,email,telephone) VALUES('Han, Fuju','FHan.China@ww2.com','432-5-828');
INSERT INTO employee(name,email,telephone) VALUES('Hansen, Erik','EHansen.Germany@ww2.com','941-158-875');
INSERT INTO employee(name,email,telephone) VALUES('Hata, Shunroku','SHata.Japan@ww2.com','674-890-785');
INSERT INTO employee(name,email,telephone) VALUES('Hausser, Paul','PHausser.Germany@ww2.com','622-449-546');
INSERT INTO employee(name,email,telephone) VALUES('Hayes, Ira','IHayes.United States@ww2.com','336-644-335');
INSERT INTO employee(name,email,telephone) VALUES('He, Yingqin','YHe.China@ww2.com','672-237-188');
INSERT INTO employee(name,email,telephone) VALUES('Heinrichs, Erik','EHeinrichs.Finland@ww2.com','421-883-862');
INSERT INTO employee(name,email,telephone) VALUES('Heitz, Walter','WHeitz.Germany@ww2.com','701-248-364');
INSERT INTO employee(name,email,telephone) VALUES('Heppner, Richard','RHeppner.United States@ww2.com','587-601-18');
INSERT INTO employee(name,email,telephone) VALUES('Herring, Edmund','EHerring.Australia@ww2.com','674-88-880');
INSERT INTO employee(name,email,telephone) VALUES('Heusinger, Adolf','AHeusinger.Germany@ww2.com','523-218-488');
INSERT INTO employee(name,email,telephone) VALUES('Heydte, Friedrich','FHeydte.Germany@ww2.com','690-6-873');
INSERT INTO employee(name,email,telephone) VALUES('Hobart, Percy','PHobart.United Kingdom@ww2.com','565-103-863');
INSERT INTO employee(name,email,telephone) VALUES('Hobby, Oveta','OHobby.United States@ww2.com','304-833-568');
INSERT INTO employee(name,email,telephone) VALUES('Hodges, Courtney','CHodges.United States@ww2.com','951-115-105');
INSERT INTO employee(name,email,telephone) VALUES('Hollis, Stanley','SHollis.United Kingdom@ww2.com','897-393-58');
INSERT INTO employee(name,email,telephone) VALUES('Homma, Masaharu','MHomma.Japan@ww2.com','373-376-553');
INSERT INTO employee(name,email,telephone) VALUES('Honda, Masaki','MHonda.Japan@ww2.com','482-231-118');
INSERT INTO employee(name,email,telephone) VALUES('Hong, Sa-ik','SHong.Korea@ww2.com','226-26-86');
INSERT INTO employee(name,email,telephone) VALUES('Honjo, Shigeru','SHonjo.Japan@ww2.com','538-886-692');
INSERT INTO employee(name,email,telephone) VALUES('Horii, Tomitaro','THorii.Japan@ww2.com','776-447-560');
INSERT INTO employee(name,email,telephone) VALUES('Hoth, Hermann','HHoth.Germany@ww2.com','723-208-200');
INSERT INTO employee(name,email,telephone) VALUES('Huntziger, Charles','CHuntziger.France@ww2.com','571-218-229');
INSERT INTO employee(name,email,telephone) VALUES('Hyakutake, Harukichi','HHyakutake.Japan@ww2.com','258-382-418');
INSERT INTO employee(name,email,telephone) VALUES('Hayha, Simo','SHayha.Finland@ww2.com','40-960-922');
INSERT INTO employee(name,email,telephone) VALUES('Ichiki, Kiyono','KIchiki.Japan@ww2.com','515-473-922');
INSERT INTO employee(name,email,telephone) VALUES('Imamura, Hitoshi','HImamura.Japan@ww2.com','13-44-668');
INSERT INTO employee(name,email,telephone) VALUES('Inoguchi, Rikihei','RInoguchi.Japan@ww2.com','83-83-590');
INSERT INTO employee(name,email,telephone) VALUES('Inouye, Daniel','DInouye.Hawaii@ww2.com','615-206-878');
INSERT INTO employee(name,email,telephone) VALUES('Ismay, Hastings','HIsmay.United Kingdom@ww2.com','941-21-443');
INSERT INTO employee(name,email,telephone) VALUES('Itagaki, Seishiro','SItagaki.Japan@ww2.com','765-803-775');
INSERT INTO employee(name,email,telephone) VALUES('Ji, Cheong-cheon','CJi.Korea@ww2.com','835-912-233');
INSERT INTO employee(name,email,telephone) VALUES('Jiang, Dingwen','DJiang.China@ww2.com','806-123-744');
INSERT INTO employee(name,email,telephone) VALUES('Jodl, Alfred','AJodl.Germany@ww2.com','641-763-82');
INSERT INTO employee(name,email,telephone) VALUES('Jany, Gusztav','GJany.Hungary@ww2.com','723-94-469');
INSERT INTO employee(name,email,telephone) VALUES('Kalugina, Klavdia','KKalugina.Russia@ww2.com','142-716-290');
INSERT INTO employee(name,email,telephone) VALUES('Keitel, Wilhelm','WKeitel.Germany@ww2.com','955-406-951');
INSERT INTO employee(name,email,telephone) VALUES('Keller, Rodney','RKeller.Canada@ww2.com','859-990-811');
INSERT INTO employee(name,email,telephone) VALUES('Kim, Young-Oak','YKim.United States@ww2.com','552-792-477');
INSERT INTO employee(name,email,telephone) VALUES('Kitano, Masaji','MKitano.Japan@ww2.com','373-931-313');
INSERT INTO employee(name,email,telephone) VALUES('Kleist, Paul','PKleist.Germany@ww2.com','591-777-259');
INSERT INTO employee(name,email,telephone) VALUES('Kluge, Ganther','GKluge.Germany@ww2.com','303-873-263');
INSERT INTO employee(name,email,telephone) VALUES('Knight, Jack','JKnight.United States@ww2.com','596-373-860');
INSERT INTO employee(name,email,telephone) VALUES('Komorowski, Tadeusz','TKomorowski.Poland@ww2.com','795-461-990');
INSERT INTO employee(name,email,telephone) VALUES('Konev, Ivan','IKonev.Russia@ww2.com','557-846-300');
INSERT INTO employee(name,email,telephone) VALUES('Kreipe, Heinrich','HKreipe.Germany@ww2.com','594-355-841');
INSERT INTO employee(name,email,telephone) VALUES('Krueger, Walter','WKrueger.United States@ww2.com','230-455-463');
INSERT INTO employee(name,email,telephone) VALUES('Kuribayashi, Tadamichi','TKuribayashi.Japan@ww2.com','761-856-629');
INSERT INTO employee(name,email,telephone) VALUES('Kuznetsov, Vasily','VKuznetsov.Russia@ww2.com','620-348-50');
INSERT INTO employee(name,email,telephone) VALUES('Kachler, Georg','GKachler.Germany@ww2.com','733-951-127');
INSERT INTO employee(name,email,telephone) VALUES('Kanig, Pierre','PKanig.France@ww2.com','1-896-224');
INSERT INTO employee(name,email,telephone) VALUES('Lanz, Hubert','HLanz.Germany@ww2.com','480-282-136');
INSERT INTO employee(name,email,telephone) VALUES('Le Suire, Karl','SL.Germany@ww2.com','887-446-822');
INSERT INTO employee(name,email,telephone) VALUES('Leeb, Wilhelm','WLeeb.Germany@ww2.com','925-726-126');
INSERT INTO employee(name,email,telephone) VALUES('Leese, Oliver','OLeese.United Kingdom@ww2.com','725-870-986');
INSERT INTO employee(name,email,telephone) VALUES('Li, Jue','JLi.China@ww2.com','56-214-901');
INSERT INTO employee(name,email,telephone) VALUES('Li, Mi','MLi.China@ww2.com','543-611-410');
INSERT INTO employee(name,email,telephone) VALUES('Li, Shouxin','SLi.China@ww2.com','620-795-654');
INSERT INTO employee(name,email,telephone) VALUES('Li, Zongren','ZLi.China@ww2.com','403-582-488');
INSERT INTO employee(name,email,telephone) VALUES('Liao, Yaoxiang','YLiao.China@ww2.com','253-589-517');
INSERT INTO employee(name,email,telephone) VALUES('List, Wilhelm','WList.Germany@ww2.com','211-83-270');
INSERT INTO employee(name,email,telephone) VALUES('Lobkovskaya, Nina','NLobkovskaya.Russia@ww2.com','599-816-475');
INSERT INTO employee(name,email,telephone) VALUES('Lu, Han','HLu.China@ww2.com','323-865-279');
INSERT INTO employee(name,email,telephone) VALUES('Ludwiger, Hartwig','HLudwiger.Germany@ww2.com','843-590-691');
INSERT INTO employee(name,email,telephone) VALUES('Lahr, Alexander','ALahr.Germany@ww2.com','373-877-464');
INSERT INTO employee(name,email,telephone) VALUES('Ma, Bufang','BMa.China@ww2.com','89-277-106');
INSERT INTO employee(name,email,telephone) VALUES('Ma, Buluan','BMa.China@ww2.com','500-736-87');
INSERT INTO employee(name,email,telephone) VALUES('Ma, Buqing','BMa.China@ww2.com','141-128-26');
INSERT INTO employee(name,email,telephone) VALUES('Ma, Zhanshan','ZMa.China@ww2.com','407-431-971');
INSERT INTO employee(name,email,telephone) VALUES('MacArthur, Douglas','DMacArthur.United States@ww2.com','628-941-50');
INSERT INTO employee(name,email,telephone) VALUES('Maczek, Stanislaw','SMaczek.Poland@ww2.com','64-537-454');
INSERT INTO employee(name,email,telephone) VALUES('Maisel, Ernst','EMaisel.Germany@ww2.com','172-150-407');
INSERT INTO employee(name,email,telephone) VALUES('Manchester, William','WManchester.United States@ww2.com','616-115-472');
INSERT INTO employee(name,email,telephone) VALUES('Mannerheim, Carl G. E.','CMannerheim.Finland@ww2.com','111-1000-910');
INSERT INTO employee(name,email,telephone) VALUES('Manstein, Erich','EManstein.Germany@ww2.com','626-501-568');
INSERT INTO employee(name,email,telephone) VALUES('Manteuffel, Hasso','HManteuffel.Germany@ww2.com','15-214-883');
INSERT INTO employee(name,email,telephone) VALUES('Marshall, George','GMarshall.United States@ww2.com','671-745-878');
INSERT INTO employee(name,email,telephone) VALUES('Maruyama, Masao','MMaruyama.Japan@ww2.com','233-788-749');
INSERT INTO employee(name,email,telephone) VALUES('Matsui, Iwane','IMatsui.Japan@ww2.com','623-991-396');
INSERT INTO employee(name,email,telephone) VALUES('Mauldin, Bill','BMauldin.United States@ww2.com','985-677-778');
INSERT INTO employee(name,email,telephone) VALUES('McAuliffe, Anthony','AMcAuliffe.United States@ww2.com','578-246-914');
INSERT INTO employee(name,email,telephone) VALUES('McNaughton, Andrew','AMcNaughton.Canada@ww2.com','594-684-956');
INSERT INTO employee(name,email,telephone) VALUES('Merrill, Frank','FMerrill.United States@ww2.com','53-857-771');
INSERT INTO employee(name,email,telephone) VALUES('Messe, Giovanni','GMesse.Italy@ww2.com','979-682-518');
INSERT INTO employee(name,email,telephone) VALUES('Mihailovic, Dragoljub','DMihailovic.Yugoslavia@ww2.com','580-328-979');
INSERT INTO employee(name,email,telephone) VALUES('Minami, Jiro','JMinami.Japan@ww2.com','319-777-130');
INSERT INTO employee(name,email,telephone) VALUES('Model, Walter','WModel.Germany@ww2.com','560-848-738');
INSERT INTO employee(name,email,telephone) VALUES('Montgomery, Bernard','BMontgomery.United Kingdom@ww2.com','580-420-996');
INSERT INTO employee(name,email,telephone) VALUES('Morshead, Leslie','LMorshead.Australia@ww2.com','696-246-697');
INSERT INTO employee(name,email,telephone) VALUES('Murphy, Audie','AMurphy.United States@ww2.com','285-223-515');
INSERT INTO employee(name,email,telephone) VALUES('Muto, Akira','AMuto.Japan@ww2.com','103-868-395');
INSERT INTO employee(name,email,telephone) VALUES('Muaoz Grandes, Agustan','GMuao.Spain@ww2.com','623-470-831');
INSERT INTO employee(name,email,telephone) VALUES('Maller, Friedrich-Wilhelm','FMaller.Germany@ww2.com','150-288-865');
INSERT INTO employee(name,email,telephone) VALUES('Nemoto, Hiroshi','HNemoto.Japan@ww2.com','62-864-880');
INSERT INTO employee(name,email,telephone) VALUES('Nishi, Takeichi','TNishi.Japan@ww2.com','556-814-136');
INSERT INTO employee(name,email,telephone) VALUES('Novikov, Petr','PNovikov.Russia@ww2.com','629-941-748');
INSERT INTO employee(name,email,telephone) VALUES('OConnor, Richard','ROConnor.United Kingdom@ww2.com','435-210-713');
INSERT INTO employee(name,email,telephone) VALUES('Obata, Hideyoshi','HObata.Japan@ww2.com','712-531-774');
INSERT INTO employee(name,email,telephone) VALUES('Oesch, Karl','KOesch.Finland@ww2.com','659-640-207');
INSERT INTO employee(name,email,telephone) VALUES('Okamura, Yasuji','YOkamura.Japan@ww2.com','688-10-47');
INSERT INTO employee(name,email,telephone) VALUES('Paik, Sun-yup','SPaik.Korea@ww2.com','342-565-264');
INSERT INTO employee(name,email,telephone) VALUES('Pajari, Aaro','APajari.Finland@ww2.com','176-756-923');
INSERT INTO employee(name,email,telephone) VALUES('Pang, Bingxun','BPang.China@ww2.com','11-582-814');
INSERT INTO employee(name,email,telephone) VALUES('Papagos, Alexandros','APapagos.Greece@ww2.com','723-628-597');
INSERT INTO employee(name,email,telephone) VALUES('Patton, George','GPatton.United States@ww2.com','655-818-9');
INSERT INTO employee(name,email,telephone) VALUES('Paulus, Friedrich','FPaulus.Germany@ww2.com','396-27-622');
INSERT INTO employee(name,email,telephone) VALUES('Pavlichenko, Lyudmila','LPavlichenko.Ukraine@ww2.com','858-964-676');
INSERT INTO employee(name,email,telephone) VALUES('Pavlov, Dmitry','DPavlov.Russia@ww2.com','625-305-651');
INSERT INTO employee(name,email,telephone) VALUES('Percival, Arthur','APercival.United Kingdom@ww2.com','848-57-178');
INSERT INTO employee(name,email,telephone) VALUES('Petrov, Ivan','IPetrov.Russia@ww2.com','192-889-163');
INSERT INTO employee(name,email,telephone) VALUES('Poorten, Hein ter','HPoorten.Netherlands@ww2.com','114-49-111');
INSERT INTO employee(name,email,telephone) VALUES('Pownall, Henry','HPownall.United Kingdom@ww2.com','700-481-431');
INSERT INTO employee(name,email,telephone) VALUES('Puller, Lewis','LPuller.United States@ww2.com','350-617-478');
INSERT INTO employee(name,email,telephone) VALUES('Reichenau, Walther','WReichenau.Germany@ww2.com','580-689-1');
INSERT INTO employee(name,email,telephone) VALUES('Reymann, Helmuth','HReymann.Germany@ww2.com','743-369-166');
INSERT INTO employee(name,email,telephone) VALUES('Roettig, Wilhelm','WRoettig.Germany@ww2.com','132-143-475');
INSERT INTO employee(name,email,telephone) VALUES('Roh, Yong-U','YRoh.Japan@ww2.com','311-678-291');
INSERT INTO employee(name,email,telephone) VALUES('Rokossovsky, Konstantin','KRokossovsky.Poland@ww2.com','218-28-691');
INSERT INTO employee(name,email,telephone) VALUES('Rommel, Erwin','ERommel.Germany@ww2.com','719-517-208');
INSERT INTO employee(name,email,telephone) VALUES('Rotmistrov, Pavel','PRotmistrov.Russia@ww2.com','101-355-558');
INSERT INTO employee(name,email,telephone) VALUES('Rowell, Sydney','SRowell.Australia@ww2.com','686-212-658');
INSERT INTO employee(name,email,telephone) VALUES('Rundstedt, Gerd','GRundstedt.Germany@ww2.com','487-95-739');
INSERT INTO employee(name,email,telephone) VALUES('Rybalko, Pavel','PRybalko.Russia@ww2.com','482-223-402');
INSERT INTO employee(name,email,telephone) VALUES('Rydz-amigay, Edward','ERydz-amigay.Poland@ww2.com','756-718-815');
INSERT INTO employee(name,email,telephone) VALUES('Saito, Yoshitsugu','YSaito.Japan@ww2.com','669-328-246');
INSERT INTO employee(name,email,telephone) VALUES('Sarafis, Stefanos','SSarafis.Greece@ww2.com','932-653-682');
INSERT INTO employee(name,email,telephone) VALUES('Sasaki, Noboru','NSasaki.Japan@ww2.com','230-949-594');
INSERT INTO employee(name,email,telephone) VALUES('Sato, Shunji','SSato.Japan@ww2.com','113-73-119');
INSERT INTO employee(name,email,telephone) VALUES('Schmidt, Kurt','KSchmidt.Germany@ww2.com','182-297-730');
INSERT INTO employee(name,email,telephone) VALUES('Schwalbe, Felix','FSchwalbe.Germany@ww2.com','723-431-523');
INSERT INTO employee(name,email,telephone) VALUES('Scharner, Ferdinand','FScharner.Germany@ww2.com','42-968-807');
INSERT INTO employee(name,email,telephone) VALUES('Sejima, Ryuzo','RSejima.Japan@ww2.com','969-110-616');
INSERT INTO employee(name,email,telephone) VALUES('Shanina, Roza','RShanina.Russia@ww2.com','22-730-719');
INSERT INTO employee(name,email,telephone) VALUES('Shaposhnikov, Boris','BShaposhnikov.Russia@ww2.com','618-773-848');
INSERT INTO employee(name,email,telephone) VALUES('Shioden, Nobutaka','NShioden.Japan@ww2.com','687-959-937');
INSERT INTO employee(name,email,telephone) VALUES('Shirakawa, Yoshinori','YShirakawa.Japan@ww2.com','450-464-289');
INSERT INTO employee(name,email,telephone) VALUES('Short, Walter','WShort.United States@ww2.com','979-226-180');
INSERT INTO employee(name,email,telephone) VALUES('Siffleet, Leonard','LSiffleet.Australia@ww2.com','531-742-541');
INSERT INTO employee(name,email,telephone) VALUES('Siilasvuo, Hjalmar','HSiilasvuo.Finland@ww2.com','847-635-359');
INSERT INTO employee(name,email,telephone) VALUES('Sikorski, Waadysaaw','WSikorski.Poland@ww2.com','950-615-679');
INSERT INTO employee(name,email,telephone) VALUES('Simonds, Guy','GSimonds.Canada@ww2.com','405-358-724');
INSERT INTO employee(name,email,telephone) VALUES('Simpson, William','WSimpson.United States@ww2.com','578-698-603');
INSERT INTO employee(name,email,telephone) VALUES('Singh, Umrao','USingh.India@ww2.com','615-487-910');
INSERT INTO employee(name,email,telephone) VALUES('Skorzeny, Otto','OSkorzeny.Austria@ww2.com','957-166-24');
INSERT INTO employee(name,email,telephone) VALUES('Slim, William','WSlim.United Kingdom@ww2.com','467-478-946');
INSERT INTO employee(name,email,telephone) VALUES('Smith, Holland','HSmith.United States@ww2.com','628-234-440');
INSERT INTO employee(name,email,telephone) VALUES('Smith, Walter','WSmith.United States@ww2.com','642-444-771');
INSERT INTO employee(name,email,telephone) VALUES('Song, Tiancai','TSong.China@ww2.com','283-815-517');
INSERT INTO employee(name,email,telephone) VALUES('Song, Zheyuan','ZSong.China@ww2.com','954-975-483');
INSERT INTO employee(name,email,telephone) VALUES('Stauffenberg, Claus','CStauffenberg.Germany@ww2.com','894-768-790');
INSERT INTO employee(name,email,telephone) VALUES('Stein, Tony','TStein.United States@ww2.com','113-660-154');
INSERT INTO employee(name,email,telephone) VALUES('Stettner von Grabenhofen, Walter','vStettne.Germany@ww2.com','341-682-976');
INSERT INTO employee(name,email,telephone) VALUES('Stilwell, Joseph','JStilwell.United States@ww2.com','715-598-801');
INSERT INTO employee(name,email,telephone) VALUES('Student, Kurt','KStudent.Germany@ww2.com','572-104-711');
INSERT INTO employee(name,email,telephone) VALUES('Sturdee, Vernon','VSturdee.Australia@ww2.com','676-334-158');
INSERT INTO employee(name,email,telephone) VALUES('Su, Yu','YSu.China@ww2.com','319-659-130');
INSERT INTO employee(name,email,telephone) VALUES('Sugiyama, Hajime','HSugiyama.Japan@ww2.com','435-848-598');
INSERT INTO employee(name,email,telephone) VALUES('Sultan, Daniel','DSultan.United States@ww2.com','881-499-817');
INSERT INTO employee(name,email,telephone) VALUES('Sun, Chu','CSun.China@ww2.com','196-261-185');
INSERT INTO employee(name,email,telephone) VALUES('Sun, Du','DSun.China@ww2.com','577-865-673');
INSERT INTO employee(name,email,telephone) VALUES('Sun, Lianzhong','LSun.China@ww2.com','497-533-171');
INSERT INTO employee(name,email,telephone) VALUES('Sun, Liren','LSun.China@ww2.com','118-754-510');
INSERT INTO employee(name,email,telephone) VALUES('Susloparov, Ivan','ISusloparov.Russia@ww2.com','15-521-919');
INSERT INTO employee(name,email,telephone) VALUES('Tanaka, Shizuichi','STanaka.Japan@ww2.com','853-4-875');
INSERT INTO employee(name,email,telephone) VALUES('Tani, Hisao','HTani.Japan@ww2.com','155-108-443');
INSERT INTO employee(name,email,telephone) VALUES('Taylor, Maxwell','MTaylor.United States@ww2.com','993-975-237');
INSERT INTO employee(name,email,telephone) VALUES('Terauchi, Hisaichi','HTerauchi.Japan@ww2.com','130-703-487');
INSERT INTO employee(name,email,telephone) VALUES('Thanarat, Sarit','SThanarat.Thailand@ww2.com','185-561-274');
INSERT INTO employee(name,email,telephone) VALUES('Timoshenko, Semyon','STimoshenko.Russia@ww2.com','837-153-933');
INSERT INTO employee(name,email,telephone) VALUES('Tito, Josip','JTito.Yugoslavia@ww2.com','376-278-950');
INSERT INTO employee(name,email,telephone) VALUES('Truscott, Lucian','LTruscott.Germany@ww2.com','736-604-457');
INSERT INTO employee(name,email,telephone) VALUES('Tsolakoglou, Georgios','GTsolakoglou.United.States@ww2.com','250-488-768');
INSERT INTO employee(name,email,telephone) VALUES('Tsuji, Masanobu','MTsuji.Japan@ww2.com','654-34-841');
INSERT INTO employee(name,email,telephone) VALUES('Tuker, Francis','FTuker.United.States@ww2.com','214-571-389');
INSERT INTO employee(name,email,telephone) VALUES('Tunku Osman','OTunk.Finland@ww2.com','923-102-304');
INSERT INTO employee(name,email,telephone) VALUES('Ueda, Kenkichi','KUeda.Finland@ww2.com','157-871-960');
INSERT INTO employee(name,email,telephone) VALUES('Umezu, Yoshijiro','YUmezu.United.Kingdom@ww2.com','58-235-358');
INSERT INTO employee(name,email,telephone) VALUES('Ushijima, Mitsuru','MUshijima.Australia@ww2.com','898-644-991');
INSERT INTO employee(name,email,telephone) VALUES('Ushiroku, Jun','JUshiroku.United.States@ww2.com','951-392-392');
INSERT INTO employee(name,email,telephone) VALUES('Vandegrift, Alexander','AVandegrift.Japan@ww2.com','505-154-762');
INSERT INTO employee(name,email,telephone) VALUES('Vasilevsky, Aleksandr','AVasilevsky.Poland@ww2.com','554-162-313');
INSERT INTO employee(name,email,telephone) VALUES('Vatutin, Nikolai','NVatutin.Japan@ww2.com','350-769-579');
INSERT INTO employee(name,email,telephone) VALUES('Vouza, Jacob','JVouza.United.States@ww2.com','218-439-608');
INSERT INTO employee(name,email,telephone) VALUES('Wada, Minoru','MWada.United.Kingdom@ww2.com','105-969-668');
INSERT INTO employee(name,email,telephone) VALUES('Wainwright, Jonathan','JWainwright.Romania@ww2.com','976-796-775');
INSERT INTO employee(name,email,telephone) VALUES('Walker, Walton','WWalker.Armenia@ww2.com','578-915-705');
INSERT INTO employee(name,email,telephone) VALUES('Wang, Mingzhang','MWang.Italy@ww2.com','33-124-348');
INSERT INTO employee(name,email,telephone) VALUES('Wang, Picheng','PWang.Armenia@ww2.com','540-371-264');
INSERT INTO employee(name,email,telephone) VALUES('Wang, Zhi','ZWang.China@ww2.com','227-686-350');
INSERT INTO employee(name,email,telephone) VALUES('Wavell, Archibald','AWavell.United.States@ww2.com','617-113-662');
INSERT INTO employee(name,email,telephone) VALUES('Wedemeyer, Albert','AWedemeyer.United.States@ww2.com','223-894-169');
INSERT INTO employee(name,email,telephone) VALUES('Wei, Daming','DWei.Belgium@ww2.com','885-576-546');
INSERT INTO employee(name,email,telephone) VALUES('Wei, Lihuang','LWei.Germany@ww2.com','849-543-13');
INSERT INTO employee(name,email,telephone) VALUES('Weichs, Maximilian','MWeichs.United.States@ww2.com','552-345-66');
INSERT INTO employee(name,email,telephone) VALUES('Weidling, Helmuth','HWeidling.Australia@ww2.com','385-452-25');
INSERT INTO employee(name,email,telephone) VALUES('Wenck, Walther','WWenck.China@ww2.com','801-32-807');
INSERT INTO employee(name,email,telephone) VALUES('Wessels, Theodore','TWessels.Germany@ww2.com','901-442-643');
INSERT INTO employee(name,email,telephone) VALUES('Weygand, Maxime','MWeygand.Australia@ww2.com','394-405-74');
INSERT INTO employee(name,email,telephone) VALUES('Willey, John','JWilley.Germany@ww2.com','615-468-811');
INSERT INTO employee(name,email,telephone) VALUES('Wingate, Orde','OWingate.Germany@ww2.com','587-243-784');
INSERT INTO employee(name,email,telephone) VALUES('Wansche, Max','MWansche.Germany@ww2.com','546-429-581');
INSERT INTO employee(name,email,telephone) VALUES('Xi Qia','QX.Poland@ww2.com','628-46-471');
INSERT INTO employee(name,email,telephone) VALUES('Xia, Chuzhong','CXia.United.States@ww2.com','666-704-870');
INSERT INTO employee(name,email,telephone) VALUES('Xiao, Yisu','YXiao.Germany@ww2.com','385-198-367');
INSERT INTO employee(name,email,telephone) VALUES('Xue, Yue','YXue.Germany@ww2.com','716-240-607');
INSERT INTO employee(name,email,telephone) VALUES('Yamada, Otozo','OYamada.Germany@ww2.com','897-157-667');
INSERT INTO employee(name,email,telephone) VALUES('Yamashita, Tomoyuki','TYamashita.Germany@ww2.com','657-483-299');
INSERT INTO employee(name,email,telephone) VALUES('Yamazaki, Yasuyo','YYamazaki.United.Kingdom@ww2.com','858-700-407');
INSERT INTO employee(name,email,telephone) VALUES('Yan, Xishan','XYan.United.States@ww2.com','913-246-588');
INSERT INTO employee(name,email,telephone) VALUES('Yi, Geon','GYi.United.Kingdom@ww2.com','8-330-793');
INSERT INTO employee(name,email,telephone) VALUES('Yi, Un','UYi.United.States@ww2.com','85-597-746');
INSERT INTO employee(name,email,telephone) VALUES('Yoshioka, Yasunori','YYoshioka.Russia@ww2.com','804-477-281');
INSERT INTO employee(name,email,telephone) VALUES('Yu, Hanmou','HYu.Germany@ww2.com','769-904-389');
INSERT INTO employee(name,email,telephone) VALUES('Zangen, Gustav-Adolf','GZangen.Germany@ww2.com','95-494-460');
INSERT INTO employee(name,email,telephone) VALUES('Zeitzler, Kurt','KZeitzler.China@ww2.com','889-335-106');
INSERT INTO employee(name,email,telephone) VALUES('Zhang, Haipeng','HZhang.United.States@ww2.com','762-847-505');
INSERT INTO employee(name,email,telephone) VALUES('Zhang, Lingfu','LZhang.Czechoslovakia@ww2.com','241-612-571');
INSERT INTO employee(name,email,telephone) VALUES('Zhang, Zhizhong','ZZhang.Italy@ww2.com','693-598-533');
INSERT INTO employee(name,email,telephone) VALUES('Zhao, Chengshou','CZhao.China@ww2.com','579-328-494');
INSERT INTO employee(name,email,telephone) VALUES('Zhao, Dengyu','DZhao.China@ww2.com','872-477-750');
INSERT INTO employee(name,email,telephone) VALUES('Zhukov, Georgy','GZhukov.China@ww2.com','664-401-646');
INSERT INTO employee(name,email,telephone) VALUES('Ohquist, Harald','Hahquist.China@ww2.com','965-551-121');